name: CI-MASTER

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Slack notification Success
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: cemkiy/action-slacker@master
      with:
        channel: '#github-ci-actions'
        icon_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        username: 'GitHub'
