name: CI-Release

on:
  release:
    types: [published, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
        REPO_OWNER: ${{ github.event.repository.owner.login }}
        RELESE_ACTOR: ${{ github.actor }}
        RELESE_AUTHER: ${{ github.release.author.login }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo $GITHUB_REF
        echo $REPO_OWNER
        echo $RELESE_ACTOR
        echo $RELESE_AUTHER
        cat README.md

